export type Category = "general" | "sexual" | "mens" | "womens";

export type Bundle = {
  id: string;
  name: string;
  category: Category;
  price: number;
  description: string;
  tests: string[];
  featured?: boolean;
};

export const CATEGORIES: { id: Category | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "general", label: "General Health" },
  { id: "sexual", label: "Sexual Health" },
  { id: "mens", label: "Men's Health" },
  { id: "womens", label: "Women's Health" },
];

export const CATEGORY_LABELS: Record<Category, string> = {
  general: "General Health",
  sexual: "Sexual Health",
  mens: "Men's Health",
  womens: "Women's Health",
};

export const BUNDLES: Bundle[] = [

  // ─── GENERAL HEALTH ────────────────────────────────────────────────────────

  {
    id: "quick-health-snapshot",
    name: "Quick Health Snapshot",
    category: "general",
    price: 15000,
    description:
      "A fast, affordable starter screen covering the essentials — ideal for a routine check or when you just want reassurance.",
    tests: [
      "Complete Blood Count",
      "Random Plasma Glucose",
      "Urinalysis",
      "Blood Film for Malaria Parasite",
      "HIV I & II (Rapid)",
      "HBsAg (Rapid)",
    ],
  },
  {
    id: "essential-health-screen",
    name: "Essential Health Screen",
    category: "general",
    price: 28000,
    description:
      "A solid foundation check for anyone wanting a reliable overview of their blood, metabolic, and infectious-disease status.",
    tests: [
      "Complete Blood Count",
      "Fasting Plasma Glucose",
      "Urinalysis",
      "Blood Group & Genotype",
      "Blood Film for Malaria Parasite",
      "HBsAg (Rapid)",
      "HIV I & II (Rapid)",
      "VDRL (Syphilis)",
    ],
  },
  {
    id: "full-body",
    name: "Full Body Check",
    category: "general",
    price: 45000,
    featured: true,
    description:
      "A comprehensive head-to-toe health assessment covering all major organ systems.",
    tests: [
      "Complete Blood Count",
      "Liver Function Test",
      "Kidney Function Test (EUCr)",
      "Fasting Lipid Profile",
      "Fasting Plasma Glucose",
      "Urinalysis",
      "Resting 12-Lead ECG",
    ],
  },
  {
    id: "annual-wellness-review",
    name: "Annual Wellness Review",
    category: "general",
    price: 65000,
    description:
      "The ideal once-a-year health check — broad coverage across blood, organs, heart, and metabolic health in one visit.",
    tests: [
      "Complete Blood Count",
      "Liver Function Test",
      "Kidney Function Test (EUCr)",
      "Fasting Lipid Profile",
      "Fasting Plasma Glucose",
      "Glycated Haemoglobin (HbA1c)",
      "Thyroid Function Test (TSH, FT3, FT4)",
      "C-Reactive Protein",
      "Urinalysis",
      "Resting 12-Lead ECG",
      "Abdominal Scan",
    ],
  },
  {
    id: "cardiac",
    name: "Cardiac Wellness",
    category: "general",
    price: 60000,
    description:
      "Advanced cardiac markers and lipid assessment for heart-health monitoring.",
    tests: [
      "Resting 12-Lead ECG",
      "Fasting Lipid Profile",
      "C-Reactive Protein",
      "Cardiac Troponin I",
      "Creatine Kinase-MB",
      "Cardiac Troponin T",
    ],
  },
  {
    id: "heart-check-plus",
    name: "Heart Check Plus",
    category: "general",
    price: 90000,
    description:
      "A deeper cardiac work-up combining ECG, key biomarkers, and vascular imaging for a thorough assessment of heart health.",
    tests: [
      "Resting 12-Lead ECG",
      "Stress ECG (Exercise Tolerance Test)",
      "Fasting Lipid Profile",
      "Cardiac Troponin I",
      "Creatine Kinase-MB",
      "C-Reactive Protein",
      "Fasting Plasma Glucose",
      "Carotid Doppler Study",
    ],
  },
  {
    id: "stroke-risk-profile",
    name: "Stroke Risk Profile",
    category: "general",
    price: 75000,
    description:
      "Targets the key modifiable risk factors for stroke — blood viscosity, vascular stiffness, glucose, and lipids.",
    tests: [
      "Fasting Lipid Profile",
      "Fasting Plasma Glucose",
      "Glycated Haemoglobin (HbA1c)",
      "C-Reactive Protein",
      "Prothrombin Time & INR",
      "APTT",
      "Resting 12-Lead ECG",
      "Carotid Doppler Study",
    ],
  },
  {
    id: "diabetes",
    name: "Diabetes Management",
    category: "general",
    price: 38000,
    description:
      "Complete diabetes monitoring panel for ongoing glucose and metabolic management.",
    tests: [
      "Fasting Plasma Glucose",
      "Glycated Haemoglobin (HbA1c)",
      "2-Hour Post-Prandial Glucose",
      "Fasting Lipid Profile",
      "Kidney Function Test (EUCr)",
      "Urinalysis",
    ],
  },
  {
    id: "diabetes-prevention",
    name: "Diabetes Prevention Check",
    category: "general",
    price: 28000,
    description:
      "Catches pre-diabetes and insulin resistance early — before symptoms appear — so you can act before it progresses.",
    tests: [
      "Fasting Plasma Glucose",
      "Oral Glucose Tolerance Test (OGTT)",
      "2-Hour Post-Prandial Glucose",
      "Glycated Haemoglobin (HbA1c)",
      "Fasting Lipid Profile",
      "Uric Acid",
    ],
  },
  {
    id: "metabolic-syndrome-screen",
    name: "Metabolic Syndrome Screen",
    category: "general",
    price: 42000,
    description:
      "Screens for the cluster of conditions — high blood sugar, blood pressure, cholesterol, and abdominal obesity — that raise heart and diabetes risk.",
    tests: [
      "Fasting Lipid Profile",
      "Total Cholesterol",
      "HDL Cholesterol",
      "LDL Cholesterol",
      "Triglycerides",
      "Fasting Plasma Glucose",
      "Glycated Haemoglobin (HbA1c)",
      "Uric Acid",
      "C-Reactive Protein",
      "Urinalysis",
    ],
  },
  {
    id: "liver",
    name: "Liver Health Panel",
    category: "general",
    price: 32000,
    description:
      "Dedicated liver-function panel for monitoring hepatic enzymes and early damage detection.",
    tests: [
      "Liver Function Test",
      "ALT (SGPT)",
      "AST (SGOT)",
      "ALP",
      "GGT",
      "Total Bilirubin",
      "Direct Bilirubin",
      "Total Protein & Albumin",
      "HBsAg (Rapid)",
      "HCV Antibody (Rapid)",
    ],
  },
  {
    id: "gut-health-screen",
    name: "Gut Health Screen",
    category: "general",
    price: 48000,
    description:
      "A targeted look at the digestive system — from stomach acid balance and pancreatic function to bowel health and hidden bleeding.",
    tests: [
      "Liver Function Test",
      "Amylase",
      "Lipase",
      "Stool Microscopy",
      "Antibody to H. Pylori",
      "H. Pylori Stool Antigen",
      "Fecal Occult Blood",
      "Abdominopelvic Scan",
      "Hepatobiliary Scan",
    ],
  },
  {
    id: "kidney-health-panel",
    name: "Kidney Health Panel",
    category: "general",
    price: 35000,
    description:
      "A focused assessment of kidney filtration, electrolyte balance, and urinary tract health.",
    tests: [
      "Kidney Function Test (EUCr)",
      "Serum Creatinine",
      "Serum Urea",
      "eGFR",
      "Sodium",
      "Potassium",
      "Urinalysis",
      "Urine MCS",
      "Renal Scan",
    ],
  },
  {
    id: "thyroid",
    name: "Thyroid Panel",
    category: "general",
    price: 28000,
    description:
      "Complete thyroid workup for detecting hypo/hyperthyroidism and monitoring thyroid health.",
    tests: [
      "Thyroid Function Test (TSH, Free T3, Free T4)",
      "Thyroid Scan",
    ],
  },
  {
    id: "bone-joint-panel",
    name: "Bone & Joint Health Panel",
    category: "general",
    price: 38000,
    description:
      "Assesses bone mineral metabolism, joint inflammation, and early arthritis risk markers.",
    tests: [
      "Calcium",
      "Phosphate",
      "Magnesium",
      "ALP (Alkaline Phosphatase)",
      "Uric Acid",
      "C-Reactive Protein",
      "ESR",
      "Rheumatoid Factor",
    ],
  },
  {
    id: "gout-arthritis-panel",
    name: "Gout & Arthritis Screen",
    category: "general",
    price: 30000,
    description:
      "Pinpoints the metabolic drivers of joint pain, gout, and inflammatory arthritis.",
    tests: [
      "Uric Acid",
      "C-Reactive Protein",
      "ESR",
      "Rheumatoid Factor",
      "Calcium",
      "ALP",
      "Complete Blood Count",
    ],
  },
  {
    id: "respiratory-health-panel",
    name: "Respiratory Health Panel",
    category: "general",
    price: 45000,
    description:
      "A thorough respiratory assessment combining imaging, microbiology, and blood markers for lung and airway health.",
    tests: [
      "Chest X-ray (PA/Lat)",
      "Complete Blood Count",
      "ESR",
      "C-Reactive Protein",
      "IgM Antibody to Tuberculosis",
      "Mantoux",
      "Sputum M/C/S",
    ],
  },
  {
    id: "infection-immunity-check",
    name: "Infection & Immunity Check",
    category: "general",
    price: 32000,
    description:
      "Quickly identifies active infections and immune status across Nigeria's most prevalent infectious diseases.",
    tests: [
      "Complete Blood Count",
      "ESR",
      "C-Reactive Protein",
      "Blood Film for Malaria Parasite",
      "Widal (Typhoid)",
      "HIV I & II (Rapid)",
      "HBsAg (Rapid)",
      "HCV Antibody (Rapid)",
    ],
  },
  {
    id: "typhoid-enteric-fever-screen",
    name: "Typhoid & Enteric Fever Screen",
    category: "general",
    price: 28000,
    description:
      "A targeted panel for suspected typhoid and enteric infections, covering serology, blood, and stool.",
    tests: [
      "Widal (Typhoid Serology)",
      "Complete Blood Count",
      "ESR",
      "Blood Culture",
      "Stool Microscopy",
      "Stool MCS",
    ],
  },
  {
    id: "inflammatory-markers-panel",
    name: "Inflammatory Markers Panel",
    category: "general",
    price: 30000,
    description:
      "Measures the body's inflammatory burden — useful for monitoring autoimmune conditions, chronic disease, and treatment response.",
    tests: [
      "C-Reactive Protein",
      "ESR",
      "Complete Blood Count",
      "Rheumatoid Factor",
      "Fibrinogen",
      "LDH",
    ],
  },
  {
    id: "comprehensive-cancer-screen",
    name: "Comprehensive Cancer Screen",
    category: "general",
    price: 95000,
    featured: true,
    description:
      "A broad tumour-marker survey combining the most clinically useful cancer antigens with blood and imaging assessment.",
    tests: [
      "AFP (Alpha Fetoprotein)",
      "CEA (Carcinoembryonic Antigen)",
      "CA-125",
      "CA 19-9",
      "CA 15-3",
      "PSA (Prostate Specific Antigen)",
      "Complete Blood Count",
      "Liver Function Test",
      "Abdominopelvic Scan",
    ],
  },
  {
    id: "vitamin-mineral-check",
    name: "Vitamin & Mineral Check",
    category: "general",
    price: 42000,
    description:
      "Identifies common nutritional deficiencies that affect energy, immunity, bone health, and mood.",
    tests: [
      "Vitamin D",
      "Calcium",
      "Magnesium",
      "Phosphate",
      "TIBC (Total Iron Binding Capacity)",
      "Complete Blood Count",
    ],
  },
  {
    id: "pre-marital-screen",
    name: "Pre-Marital Health Screen",
    category: "general",
    price: 35000,
    description:
      "The essential compatibility and infection screen recommended before marriage — covering genotype, blood group, and key infectious diseases.",
    tests: [
      "Blood Group & Genotype",
      "Haemoglobin Electrophoresis",
      "HIV I & II (Rapid)",
      "HBsAg (Qualitative)",
      "HCV Antibody (Rapid)",
      "VDRL (Syphilis)",
    ],
  },
  {
    id: "pre-employment-clearance",
    name: "Pre-Employment Health Clearance",
    category: "general",
    price: 38000,
    description:
      "Meets standard occupational health requirements for pre-employment medical fitness certification.",
    tests: [
      "Complete Blood Count",
      "Urinalysis",
      "Chest X-ray (PA/Lat)",
      "HBsAg (Rapid)",
      "HIV I & II (Rapid)",
      "VDRL (Syphilis)",
      "Blood Group & Genotype",
      "Random Plasma Glucose",
      "Drug of Abuse Screen",
    ],
  },
  {
    id: "corporate-wellness-bronze",
    name: "Corporate Wellness — Bronze",
    category: "general",
    price: 48000,
    description:
      "An accessible corporate health check covering the fundamentals of employee wellness with minimal disruption to the workday.",
    tests: [
      "Complete Blood Count",
      "Fasting Plasma Glucose",
      "Fasting Lipid Profile",
      "Urinalysis",
      "HBsAg (Rapid)",
      "HIV I & II (Rapid)",
      "Resting 12-Lead ECG",
      "Chest X-ray",
    ],
  },
  {
    id: "corporate-wellness-silver",
    name: "Corporate Wellness — Silver",
    category: "general",
    price: 75000,
    description:
      "A deeper corporate screen extending to organ function, diabetes control, and vascular risk — ideal for mid-career employees.",
    tests: [
      "Complete Blood Count",
      "Liver Function Test",
      "Kidney Function Test (EUCr)",
      "Fasting Lipid Profile",
      "Fasting Plasma Glucose",
      "Glycated Haemoglobin (HbA1c)",
      "Urinalysis",
      "Urine MCS",
      "HBsAg (Rapid)",
      "HIV I & II (Rapid)",
      "VDRL (Syphilis)",
      "Resting 12-Lead ECG",
      "Chest X-ray (PA/Lat)",
      "Abdominal Scan",
    ],
  },
  {
    id: "corporate-wellness-gold",
    name: "Corporate Wellness — Gold",
    category: "general",
    price: 120000,
    description:
      "Our most comprehensive corporate health package — full-system coverage for senior professionals and executives.",
    tests: [
      "Complete Blood Count",
      "Liver Function Test",
      "Kidney Function Test (EUCr)",
      "Fasting Lipid Profile",
      "Fasting Plasma Glucose",
      "Glycated Haemoglobin (HbA1c)",
      "Thyroid Function Test",
      "C-Reactive Protein",
      "Urinalysis",
      "Urine MCS",
      "HBsAg (Qualitative)",
      "HIV I & II (Rapid)",
      "VDRL (Syphilis)",
      "Resting 12-Lead ECG",
      "Stress ECG",
      "Chest X-ray (PA/Lat)",
      "Abdominopelvic Scan",
    ],
  },
  {
    id: "neonatal-essentials",
    name: "Neonatal Essentials",
    category: "general",
    price: 18000,
    description:
      "Key newborn screening tests to detect common and treatable conditions in the first days of life.",
    tests: [
      "Packed Cell Volume (Neonate)",
      "Haemoglobin (Neonate)",
      "Blood Group",
      "Genotype",
      "Total Bilirubin",
      "Direct Bilirubin",
      "Indirect Bilirubin",
    ],
  },
  {
    id: "sickle-cell-monitoring",
    name: "Sickle Cell Monitoring",
    category: "general",
    price: 40000,
    description:
      "A structured monitoring panel for patients with sickle cell disease, tracking organ function and crisis risk.",
    tests: [
      "Complete Blood Count",
      "Haemoglobin Electrophoresis",
      "Blood Group & Genotype",
      "Liver Function Test",
      "Kidney Function Test (EUCr)",
      "Urinalysis",
      "Urine MCS",
    ],
  },

  // ─── SEXUAL HEALTH ──────────────────────────────────────────────────────────

  {
    id: "std-basic",
    name: "STI Rapid Screen",
    category: "sexual",
    price: 25000,
    description:
      "A quick, confidential check for the most common sexually transmitted infections — results within the hour.",
    tests: [
      "HIV I & II (Rapid)",
      "HBsAg (Rapid)",
      "HCV Antibody (Rapid)",
      "VDRL (Syphilis — Rapid)",
      "Pregnancy Test — hCG (Rapid)",
    ],
  },
  {
    id: "std-plus",
    name: "STI Complete Panel",
    category: "sexual",
    price: 55000,
    featured: true,
    description:
      "Our most thorough STI check — covers bacterial, viral, and parasitic infections for complete peace of mind.",
    tests: [
      "HIV I & II (Rapid)",
      "HBsAg (Qualitative)",
      "HCV Antibody (Rapid)",
      "VDRL (Syphilis)",
      "HSV I & II Antibody",
      "Neisseria Gonorrhoeae Antigen",
      "Chlamydia Antigen",
      "HPV Antigen",
    ],
  },
  {
    id: "std-premium",
    name: "STI Shield Plus",
    category: "sexual",
    price: 80000,
    description:
      "Extended sexual health panel adding microbiological culture to confirm and characterise any identified infections.",
    tests: [
      "HIV I & II (Rapid)",
      "HBsAg (Qualitative)",
      "HCV Antibody (Rapid)",
      "VDRL (Syphilis)",
      "HSV I & II Antibody",
      "Neisseria Gonorrhoeae Antigen",
      "Chlamydia Antigen",
      "HPV Antigen",
      "HVS — High Vaginal Swab MCS",
      "Urethral Swab MCS",
    ],
  },
  {
    id: "hpv-cervical-shield",
    name: "HPV & Cervical Health Screen",
    category: "sexual",
    price: 45000,
    description:
      "Focused on cervical and vaginal health — combining HPV detection, infection culture, and pelvic imaging.",
    tests: [
      "HPV Antigen",
      "HVS — High Vaginal Swab MCS",
      "Endocervical Swab MCS",
      "Pelvic Scan",
      "HBsAg (Rapid)",
      "HIV I & II (Rapid)",
    ],
  },
  {
    id: "pre-conception-partner-check",
    name: "Pre-Conception Partner Check",
    category: "sexual",
    price: 45000,
    description:
      "A shared couples screen covering compatibility, infections, and key markers before trying to conceive.",
    tests: [
      "Blood Group & Genotype",
      "Haemoglobin Electrophoresis",
      "HIV I & II (Rapid)",
      "HBsAg (Qualitative)",
      "HCV Antibody (Rapid)",
      "VDRL (Syphilis)",
      "HSV I & II Antibody",
    ],
  },

  // ─── MEN'S HEALTH ──────────────────────────────────────────────────────────

  {
    id: "mens-essential",
    name: "Men's Essential Check",
    category: "mens",
    price: 42000,
    description:
      "A practical everyday screen for men, covering blood health, heart risk, prostate, and metabolic markers.",
    tests: [
      "Complete Blood Count",
      "Fasting Plasma Glucose",
      "Fasting Lipid Profile",
      "PSA (Prostate Specific Antigen)",
      "Testosterone (Male)",
      "Urinalysis",
      "Resting 12-Lead ECG",
    ],
  },
  {
    id: "mens-pro",
    name: "Men's Health Pro",
    category: "mens",
    price: 65000,
    featured: true,
    description:
      "Targeted screening for prostate, hormonal, and metabolic male-health concerns.",
    tests: [
      "PSA (Prostate Specific Antigen)",
      "Testosterone (Male)",
      "Hormonal Profile (Male)",
      "Complete Blood Count",
      "Fasting Lipid Profile",
      "Liver Function Test",
      "Kidney Function Test (EUCr)",
      "Resting 12-Lead ECG",
    ],
  },
  {
    id: "prostate-urinary-health",
    name: "Prostate & Urinary Health",
    category: "mens",
    price: 50000,
    description:
      "A dedicated work-up for men with urinary symptoms or elevated prostate risk — combining markers, culture, and imaging.",
    tests: [
      "PSA (Prostate Specific Antigen)",
      "Urinalysis",
      "Urine MCS",
      "Prostatic Fluid MCS",
      "Renal Scan",
      "Urinary Bladder Scan",
      "Transrectal Scan",
    ],
  },
  {
    id: "male-fertility-panel",
    name: "Male Fertility Panel",
    category: "mens",
    price: 60000,
    description:
      "A comprehensive fertility assessment for men — evaluating sperm quality, hormonal drivers, and testicular structure.",
    tests: [
      "Seminalysis",
      "Seminalysis, Culture & Sensitivity",
      "Testosterone (Male)",
      "FSH",
      "LH",
      "Prolactin",
      "Scrotal Scan",
      "Scrotal Doppler Study",
    ],
  },
  {
    id: "mens-hormone-balance",
    name: "Men's Hormone Balance",
    category: "mens",
    price: 55000,
    description:
      "Measures the key hormones that drive energy, libido, muscle mass, and mood in men.",
    tests: [
      "Testosterone (Male)",
      "Hormonal Profile (Male)",
      "Prolactin",
      "FSH",
      "LH",
      "Cortisol",
      "Thyroid Function Test",
    ],
  },
  {
    id: "mens-heart-health",
    name: "Men's Heart Health",
    category: "mens",
    price: 85000,
    description:
      "A targeted cardiac screen for men, combining exercise and resting ECG with key cardiac biomarkers.",
    tests: [
      "Resting 12-Lead ECG",
      "Stress ECG (Exercise Tolerance Test)",
      "Fasting Lipid Profile",
      "Cardiac Troponin I",
      "Creatine Kinase-MB",
      "Cardiac Troponin T",
      "C-Reactive Protein",
      "Fasting Plasma Glucose",
    ],
  },
  {
    id: "mens-kidney-urinary",
    name: "Men's Kidney & Urinary Focus",
    category: "mens",
    price: 45000,
    description:
      "Monitors kidney function and urinary tract health — relevant for men with diabetes, hypertension, or recurrent infections.",
    tests: [
      "Kidney Function Test (EUCr)",
      "Serum Creatinine",
      "eGFR",
      "Urinalysis",
      "Urine MCS",
      "Renal Scan",
      "Renal Doppler Study",
      "Urinary Bladder Scan",
    ],
  },
  {
    id: "active-man-performance",
    name: "Active Man Performance Check",
    category: "mens",
    price: 48000,
    description:
      "Designed for physically active men — checks iron, energy metabolism, hormones, and muscle enzyme markers.",
    tests: [
      "Complete Blood Count",
      "Testosterone (Male)",
      "Cortisol",
      "Fasting Plasma Glucose",
      "Fasting Lipid Profile",
      "Uric Acid",
      "ESR",
      "C-Reactive Protein",
      "Urinalysis",
    ],
  },
  {
    id: "executive",
    name: "Executive Health Screen",
    category: "mens",
    price: 130000,
    description:
      "The ultimate screen for busy professionals — complete organ, cardiac, hormonal, and systems assessment.",
    tests: [
      "Complete Blood Count",
      "Liver Function Test",
      "Kidney Function Test (EUCr)",
      "Fasting Lipid Profile",
      "Fasting Plasma Glucose",
      "Glycated Haemoglobin (HbA1c)",
      "Thyroid Function Test",
      "PSA (Prostate Specific Antigen)",
      "Testosterone (Male)",
      "AFP, CEA (Cancer Markers)",
      "C-Reactive Protein",
      "Resting 12-Lead ECG",
      "Stress ECG",
      "Chest X-ray (PA/Lat)",
      "Abdominopelvic Scan",
    ],
  },

  // ─── WOMEN'S HEALTH ─────────────────────────────────────────────────────────

  {
    id: "womens-essential",
    name: "Women's Essential Check",
    category: "womens",
    price: 45000,
    description:
      "A practical everyday health screen for women, covering blood, metabolic, hormonal, and pelvic health.",
    tests: [
      "Complete Blood Count",
      "Fasting Plasma Glucose",
      "Fasting Lipid Profile",
      "Hormonal Profile (Female)",
      "Urinalysis",
      "Pelvic Scan",
      "Thyroid Function Test",
    ],
  },
  {
    id: "womens",
    name: "Women's Wellness Complete",
    category: "womens",
    price: 80000,
    featured: true,
    description:
      "Comprehensive female-health panel covering hormonal, reproductive, and metabolic wellbeing.",
    tests: [
      "Complete Blood Count",
      "Liver Function Test",
      "Kidney Function Test (EUCr)",
      "Fasting Lipid Profile",
      "Hormonal Profile (Female)",
      "Thyroid Function Test",
      "Pelvic Scan",
      "Breast Scan",
      "HIV I & II (Rapid)",
      "HBsAg (Rapid)",
    ],
  },
  {
    id: "fertility",
    name: "Fertility Screening",
    category: "womens",
    price: 75000,
    description:
      "Targeted reproductive-health assessment for women planning a pregnancy or monitoring fertility.",
    tests: [
      "AMH (Anti-Müllerian Hormone)",
      "FSH",
      "LH",
      "Oestradiol (E2)",
      "Progesterone (Female)",
      "Prolactin",
      "Thyroid Function Test",
      "Transvaginal Scan",
      "Pelvic Scan",
    ],
  },
  {
    id: "antenatal-booking-screen",
    name: "Antenatal Booking Screen",
    category: "womens",
    price: 45000,
    description:
      "The recommended first-visit antenatal panel — covering infection status, blood compatibility, and early pregnancy assessment.",
    tests: [
      "Complete Blood Count",
      "Blood Group & Genotype",
      "HIV I & II (Rapid)",
      "HBsAg (Qualitative)",
      "HCV Antibody (Rapid)",
      "VDRL (Syphilis)",
      "Widal (Typhoid)",
      "Blood Film for Malaria Parasite",
      "Urinalysis",
      "Obstetric Scan (Dating / 1st Trimester)",
    ],
  },
  {
    id: "pregnancy-monitoring",
    name: "Pregnancy Monitoring Panel",
    category: "womens",
    price: 35000,
    description:
      "Routine mid- and late-pregnancy checks to monitor maternal and foetal wellbeing throughout gestation.",
    tests: [
      "Complete Blood Count",
      "Fasting Plasma Glucose",
      "Urinalysis",
      "Urine MCS",
      "Obstetric Scan (Growth / 3rd Trimester)",
      "Foetal Well Being",
      "Foetal Doppler Study",
    ],
  },
  {
    id: "breast-health-screen",
    name: "Breast Health Screen",
    category: "womens",
    price: 40000,
    description:
      "A combined imaging and biomarker screen for proactive breast health monitoring and early detection.",
    tests: [
      "Breast Scan",
      "Axillary Scan",
      "CA 15-3 (Breast Cancer Marker)",
      "CEA",
      "Complete Blood Count",
      "Liver Function Test",
    ],
  },
  {
    id: "menopause-hormonal-health",
    name: "Menopause & Hormonal Balance",
    category: "womens",
    price: 70000,
    description:
      "A thorough hormonal and metabolic panel for women navigating peri-menopause or post-menopause.",
    tests: [
      "Hormonal Profile (Female)",
      "FSH",
      "LH",
      "Oestradiol (E2)",
      "Progesterone (Female)",
      "Prolactin",
      "Thyroid Function Test",
      "Calcium",
      "Phosphate",
      "ALP",
      "Cortisol",
      "Fasting Lipid Profile",
    ],
  },
  {
    id: "pcos-screen",
    name: "Polycystic Ovary Screen",
    category: "womens",
    price: 65000,
    description:
      "Designed to identify and characterise PCOS — combining the hormonal, metabolic, and ultrasound criteria used in diagnosis.",
    tests: [
      "Hormonal Profile (Female)",
      "Testosterone (Female)",
      "FSH",
      "LH",
      "Prolactin",
      "Fasting Plasma Glucose",
      "Fasting Lipid Profile",
      "Thyroid Function Test",
      "Pelvic Scan",
      "Transvaginal Scan",
    ],
  },
  {
    id: "womens-heart-health",
    name: "Women's Heart Health",
    category: "womens",
    price: 68000,
    description:
      "Heart disease is underdiagnosed in women. This panel screens for the unique hormonal and metabolic cardiovascular risk factors in females.",
    tests: [
      "Resting 12-Lead ECG",
      "Fasting Lipid Profile",
      "Fasting Plasma Glucose",
      "Glycated Haemoglobin (HbA1c)",
      "C-Reactive Protein",
      "Cardiac Troponin I",
      "Thyroid Function Test",
      "Complete Blood Count",
    ],
  },
  {
    id: "cervical-reproductive-health",
    name: "Cervical & Reproductive Health",
    category: "womens",
    price: 48000,
    description:
      "A focused screen for cervical infections, STIs, and lower reproductive tract health.",
    tests: [
      "HPV Antigen",
      "HVS — High Vaginal Swab MCS",
      "Endocervical Swab MCS",
      "Chlamydia Antigen",
      "Neisseria Gonorrhoeae Antigen",
      "Transvaginal Scan",
      "Pelvic Scan",
      "HIV I & II (Rapid)",
      "HBsAg (Rapid)",
    ],
  },
  {
    id: "womens-comprehensive",
    name: "Women's Comprehensive Screen",
    category: "womens",
    price: 140000,
    description:
      "Our most complete female health package — whole-body coverage from blood and organs to reproductive and cardiac health.",
    tests: [
      "Complete Blood Count",
      "Liver Function Test",
      "Kidney Function Test (EUCr)",
      "Fasting Lipid Profile",
      "Fasting Plasma Glucose",
      "Glycated Haemoglobin (HbA1c)",
      "Hormonal Profile (Female)",
      "Thyroid Function Test",
      "CA-125",
      "CA 15-3",
      "CEA",
      "C-Reactive Protein",
      "HIV I & II (Rapid)",
      "HBsAg (Qualitative)",
      "Resting 12-Lead ECG",
      "Chest X-ray (PA/Lat)",
      "Breast Scan",
      "Pelvic Scan",
      "Abdominopelvic Scan",
    ],
  },
];
